/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ConditionalProperties: typeof import('./src/components/Workflow/NodeProperties/ConditionalProperties.vue')['default']
    ConnectionHitboxes: typeof import('./src/components/Workflow/ConnectionHitboxes.vue')['default']
    ContextMenu: typeof import('./src/components/Workflow/ContextMenu.vue')['default']
    DetailPanel: typeof import('./src/components/Panel/DetailPanel.vue')['default']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    InputPanel: typeof import('./src/components/Panel/InputPanel.vue')['default']
    IOEditor: typeof import('./src/components/Workflow/NodeProperties/IOEditor.vue')['default']
    KnowledgeProperties: typeof import('./src/components/Workflow/NodeProperties/KnowledgeProperties.vue')['default']
    LLMPromptEditor: typeof import('./src/components/Workflow/NodeProperties/LLMPromptEditor.vue')['default']
    LLMProperties: typeof import('./src/components/Workflow/NodeProperties/LLMProperties.vue')['default']
    NodeLibrary: typeof import('./src/components/Workflow/NodeLibrary.vue')['default']
    OutputProperties: typeof import('./src/components/Workflow/NodeProperties/OutputProperties.vue')['default']
    PathsRenderer: typeof import('./src/components/Workflow/PathsRenderer.vue')['default']
    PropertyEditor: typeof import('./src/components/Workflow/PropertyEditor.vue')['default']
    PublishDialog: typeof import('./src/components/Workflow/PublishDialog.vue')['default']
    ResultPanel: typeof import('./src/components/Panel/ResultPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RunPanel: typeof import('./src/components/Workflow/RunPanel.vue')['default']
    SearchProperties: typeof import('./src/components/Workflow/NodeProperties/SearchProperties.vue')['default']
    StartProperties: typeof import('./src/components/Workflow/NodeProperties/StartProperties.vue')['default']
    TracePanel: typeof import('./src/components/Panel/TracePanel.vue')['default']
    VariableSuggestions: typeof import('./src/components/Workflow/NodeProperties/VariableSuggestions.vue')['default']
    WorkflowCanvas: typeof import('./src/components/Workflow/WorkflowCanvas.vue')['default']
    WorkflowNode: typeof import('./src/components/Workflow/WorkflowNode.vue')['default']
    WorkflowToolbar: typeof import('./src/components/Workflow/WorkflowToolbar.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
